import { createSlice } from '@reduxjs/toolkit';
import { fetchPets } from '../actions/fetchPets';

// Create a Redux slice for managing pets.
export const petsSlice = createSlice({
  name: 'pets', // Name of the slice
  initialState: [], // Initial state of the slice
  reducers: {}, // Redux actions (if any)
  extraReducers: (builder) => {
    // Handle the fulfilled action of the fetchPets asynchronous action
    builder.addCase(fetchPets.fulfilled, (state, action) => {
      // Update the state with the fetched pets data
      return action.payload;
    });
  },
});

// Export the reducer function generated by createSlice
export default petsSlice.reducer;
